config/routes.rb
CharacterGenerator::Application.routes.draw do
  resources :players

  resources :characters

  match "/generate" => "characters#generate"

end

app/models/character.rb
class Character < ActiveRecord::Base
	belongs_to :player
end

app/models/player.rb
class Player < ActiveRecord::Base
	has_many :characters 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  # GET /characters
  # GET /characters.json

  def generate
    1.times do
      @str = rand(1..6) + rand(1..6) + rand(1..6)
    end

     @character = Character.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @character }
    end
  end

  def index
    @characters = Character.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @characters }
    end
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    @character = Character.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/new
  # GET /characters/new.json
  def new
    @character = Character.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/1/edit
  def edit
    @character = Character.find(params[:id])
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(params[:character])

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render json: @character, status: :created, location: @character }
      else
        format.html { render action: "new" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /characters/1
  # PUT /characters/1.json
  def update
    @character = Character.find(params[:id])

    respond_to do |format|
      if @character.update_attributes(params[:character])
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.json
  def index
    @players = Player.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/new
  # GET /players/new.json
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: @player }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/characters/_form.html.erb
<%= button_to "Generar", :action => "generate"  %>

<%= simple_form_for(@character) do |f| %>

    <%= f.association :player, :as => :radio_buttons %>
  
    <%= f.input :name, :wrapper_html => { :class => 'field'} %>    
 
    <%= f.input :strong, :wrapper_html => { :class => 'field', :value => @srt} %>

    <%= f.input :intelligent, :wrapper_html => { :class => 'field'} %>

    <%= f.input :dexterity, :wrapper_html => { :class => 'field'} %>

    <%= f.input :constitution, :wrapper_html => { :class => 'field'} %>

    <%= f.input :wisdom, :wrapper_html => { :class => 'field'} %>

    <%= f.input :charisma, :wrapper_html => { :class => 'field'} %>

    <%= f.button :submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Strong</th>
    <th>Intelligent</th>
    <th>Dexterity</th>
    <th>Constitution</th>
    <th>Wisdom</th>
    <th>Charisma</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @characters.each do |character| %>
  <tr>
    <td><%= character.name %></td>
    <td><%= character.strong %></td>
    <td><%= character.intelligent %></td>
    <td><%= character.dexterity %></td>
    <td><%= character.constitution %></td>
    <td><%= character.wisdom %></td>
    <td><%= character.charisma %></td>
    <td><%= link_to 'Show', character %></td>
    <td><%= link_to 'Edit', edit_character_path(character) %></td>
    <td><%= link_to 'Destroy', character, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @character.name %>
</p>

<p>
  <b>Strong:</b>
  <%= @character.strong %>
</p>

<p>
  <b>Intelligent:</b>
  <%= @character.intelligent %>
</p>

<p>
  <b>Dexterity:</b>
  <%= @character.dexterity %>
</p>

<p>
  <b>Constitution:</b>
  <%= @character.constitution %>
</p>

<p>
  <b>Wisdom:</b>
  <%= @character.wisdom %>
</p>

<p>
  <b>Charisma:</b>
  <%= @character.charisma %>
</p>


<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CharacterGenerator</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/_form.html.erb
<%= simple_form_for(@player) do |f| %>
  
    <%= f.input :name, :wrapper_html => { :class => 'field'}  %>   
 
    <%= f.button :submit %>
  
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.name %></td>
    <td><%= link_to 'Show', player %></td>
    <td><%= link_to 'Edit', edit_player_path(player) %></td>
    <td><%= link_to 'Destroy', player, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @player.name %>
</p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>